package com.samsung.android.hardware.sensormanager

enum class SemSensor(i: Int) {
        TYPE_ACTIVITY_TRACKER(8)
        ,TYPE_AFE_LOGGING ( 22)
        ,TYPE_ALTITUDE ( 18)
        ,TYPE_AUTO_DYNAMIC_WORKOUT ( 11)
        ,TYPE_AUTO_ROTATION ( 16)
        ,TYPE_AUTO_SESSION ( 10)
        ,TYPE_AUTO_SWIMMING(6)
        ,TYPE_BIA ( 38)
        ,TYPE_BP_CONTINUOUS ( 29)
        ,TYPE_BP_MANUAL ( 28)
        ,TYPE_COMMON (255)
        ,TYPE_CYCLE_MONITOR ( 47)
        ,TYPE_DAILY_HR ( 25)
        ,TYPE_ECG ( 27)
        ,TYPE_EXERCISE( 2)
        ,TYPE_EXERCISE_CALORIE( 3)
        ,TYPE_EXTERNAL_BT ( 14)
        ,TYPE_FALL_DETECTION ( 12)
        ,TYPE_GPS ( 51)
        ,TYPE_HAND_WASH ( 17)
        ,TYPE_HR ( 24)
        ,TYPE_HR_LOGGING ( 23)
        ,TYPE_HR_RAW ( 40)
        ,TYPE_INACTIVE_TIME ( 41)
        ,TYPE_INDOOR_SWIMMING( 4)
        ,TYPE_MOVEMENT ( 15)
        ,TYPE_OUTDOOR_SWIMMING( 5)
        ,TYPE_PEDOMETER( 1)
        ,TYPE_PPG ( 26)
        ,TYPE_PPG_IHRN ( 37)
        ,TYPE_RAW_INJECTOR ( 53)
        ,TYPE_REG_CTRL ( 44)
        ,TYPE_REP_COUNT ( 42)
        ,TYPE_RUNNING_DYNAMICS ( 13)
        ,TYPE_SCONTEXT( 0)
        ,TYPE_SLEEP_ANALYZER ( 31)
        ,TYPE_SLEEP_DETECTOR ( 30)
        ,TYPE_SLEEP_DETECT_FEATURE ( 48)
        ,TYPE_SLEEP_WATCH_SPO2 ( 49)
        ,TYPE_SLOCATION ( 19)
        ,TYPE_SPO2_CONTINUOUS ( 36)
        ,TYPE_SPO2_MANUAL ( 35)
        ,TYPE_STAIR_TRACKER( 7)
        ,TYPE_STATISTIC ( 52)
        ,TYPE_STEP_LEVEL( 9)
        ,TYPE_STRESS ( 32)
        ,TYPE_SWEAT_LOSS ( 39)
        ,TYPE_VO2 ( 33)
        ,TYPE_VO2_RAW ( 34)
        ,TYPE_WEAR_SKIN_TEMPERATURE ( 50)
        ,TYPE_WHEEL_CHAIR ( 46)
//    @Deprecated("")
//    val TYPE_ARM_CROSS  43
//    @Deprecated("")
//    val TYPE_WEAR_BODY_TEMPERATURE  45
}